### ISSUE TITLE
Using the SNOMED data files in the `icht` branch for data validation

### ISSUE THREAD

**Issue by vvcb** [MattStammers/hdruk_avoidable_admissions_collaboration_docs#5]
Hi @ccarenzoIC, 

@quindavies and I have been working away at the data extraction and validation bits of the pipeline at LTH.  @quindavies has done all the heavy lifting in SQL + Python to ensure that the data passes validation as setup in <https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/data/validate.py>.  

We have used [Pandera](https://pandera.readthedocs.io/) for validation - imagine [Pydantic](https://docs.pydantic.dev/) on steroids for dataframes. It generates output like below which we use iteratively to address source data quality. Quin will present this work at the next analyst meeting - our rationale is that if every site ensured that their data passes validation, the subsequent analytics code can be shared between sites with a reasonable expectation of working.

![image](https://user-images.githubusercontent.com/8311806/213870516-f3bcbf19-36e9-467f-9b67-b72ef4b3e253.png)

@MattStammers has suggested incorporating some dummy/synthetic data into the repo to demonstrate how the validation works.

In the meantime, I have been looking at <https://github.com/MattStammers/hdruk_avoidable_admissions_collaboration_docs/tree/icht/datafiles> in the [`icht` branch](https://github.com/MattStammers/hdruk_avoidable_admissions_collaboration_docs/tree/icht) and wonder if some of this should be incorporated into the validation step. For instance, the SNOMED codes in some of the columns in the source data should be a member of the SNOMED codes listed in these data files. 

@lthtr-dst joined this party a little late and are playing catch-up - so could use some guidance to make ourselves more useful.

**Comment by ccarenzoIC** [comment]
Hi Vishnu,

Thanks for working on the data validation steps. Will take a look at the suggested documentation and code.

Regarding the datafiles at the icht branch:

The protocol mentions that "_summary statistics will be calculated by relevant subgroups such as attendances for ACSCs vs attendances for Non-ACSCs_". Since ACSCs were provided with ICD10 codes ( codes_to_map.csv from Ambulatory care sensitive conditions: terminology and disease coding need to be more specific to aid policy makers and clinicians and codes_to_map_v2.csv from Directory of AmbulatoryEmergency Care for Adults), and ECDS codes are codified with SNOMED, I've done the mapping to SNOMED codes using the https://ontology.nhs.uk/production1/fhir/ConceptMap/translate endpoint and querying the concepts associated to them using the terminology browser out_df_snomed_browser.csv, out_df_snapper_snomed_browser.csv, out_df_snapper.csv). 

However, not all the resulting conditions belong to the ECDS dataset (ECDS_codes.csv from https://termbrowser.nhs.uk/?perspective=full&conceptId1=991411000000109&edition=uk-edition&release=v20221123&server=https://termbrowser.nhs.uk/sct-browser-api/snomed&langRefset=900000000000508004) so once I got the SNOMED codes, I filtered them accordingly.  

Finally, I've used the https://ontology.nhs.uk/production1/fhir/ValueSet/expand endpoint for obtaining for each of the codes, the ones from previous versions. 

The final files is **ECDS_codes_mapping.csv (applying filter of ECDS)**. 

Therefore, validation should be performed once the grouping is required, or an additional Boolean column could be added to indicate whether the diagnosis belongs to the ACSC subset.

Let me know if this  is clear. 

Thanks!

**Comment by ccarenzoIC** [comment]
Also, I was wondering, wouldn't it be useful to incorporate SNOMED codes from previous editions using the https://ontology.nhs.uk/production1/fhir/ValueSet/expand endpoint at https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/data/nhsdd_snomed.py ? This would help to incorporate records with older snomed editions, and then could be standardised with the latest edition of SNOMED-GB (2019-10-01).

**Comment by vvcb** [comment]
@ccarenzoIC , happy to look at this. Don't have API credentials yet and have discovered <https://pathling.csiro.au/> over the weekend. So, a few things to play with. But you are right - will be useful to have a reproducible way of generating valid code lists for the entire team.

Once we have the valid codes for each of the col;umns that require SNOMED CT codes, it will be easy to get Pandera to validate the dataframe to ensure only these codes are present on those columns.

**Comment by MattStammers** [comment]
Nice work guys. Pandera looks like a good choice.

**Comment by MattStammers** [comment]
I'm going to close this because the work that you guys and @dfleming9 are currently doing is very likely to address the above
